.set VP8BORDERINPIXELS_VAL                   ,    32
.set yv12_buffer_config_border               ,    68
.set yv12_buffer_config_u_buffer             ,    48
.set yv12_buffer_config_uv_height            ,    24
.set yv12_buffer_config_uv_stride            ,    28
.set yv12_buffer_config_uv_width             ,    20
.set yv12_buffer_config_v_buffer             ,    52
.set yv12_buffer_config_y_buffer             ,    44
.set yv12_buffer_config_y_height             ,     4
.set yv12_buffer_config_y_stride             ,    16
.set yv12_buffer_config_y_width              ,     0
